# Generated by Django 4.2.17 on 2025-01-14 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='last_effect_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
