# Generated by Django 4.2.17 on 2025-01-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_last_study_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='boss_defeated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='coin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
