# Generated by Django 4.2.17 on 2025-01-14 16:43

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_last_study_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_study_date',
            field=models.DateField(blank=True, default=account.models.default_last_study_date, null=True),
        ),
    ]
