# Generated by Django 4.2.17 on 2025-01-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_last_study_date_profile_level_profile_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
